import type {
  StampCategory,
  StampCategoryInfo,
  InstrumentDefinition,
} from '@/types/stamp-duty';
import { SALE_DEED_SLABS, FAMILY_LOCATION_FEES } from './rates';

// ── 8 Category Definitions ───────────────────────────────────────────────────

export const STAMP_CATEGORIES: readonly StampCategoryInfo[] = [
  {
    id: 'conveyance',
    label: 'Conveyance',
    description: 'Sale deeds, agreements to sell, JDA, exchange',
    icon: '\u{1F3E0}',
  },
  {
    id: 'gift_release',
    label: 'Gift / Release',
    description: 'Gift, release, and settlement deeds',
    icon: '\u{1F381}',
  },
  {
    id: 'mortgage',
    label: 'Mortgage',
    description: 'Mortgage deeds and title deed deposits',
    icon: '\u{1F3E6}',
  },
  {
    id: 'lease',
    label: 'Lease',
    description: 'Transfer and surrender of lease',
    icon: '\u{1F4C4}',
  },
  {
    id: 'power_of_attorney',
    label: 'Power of Attorney',
    description: 'POA for property sale and general POA',
    icon: '\u{1F58A}',
  },
  {
    id: 'partition',
    label: 'Partition',
    description: 'Partition of property (agriculture & non-agriculture)',
    icon: '\u2702',
  },
  {
    id: 'trust_will',
    label: 'Trust & Will',
    description: 'Trust deeds, wills, and cancellations',
    icon: '\u{1F4DC}',
  },
  {
    id: 'miscellaneous',
    label: 'Miscellaneous',
    description: 'Adoption deed, affidavit, and others',
    icon: '\u{1F4CB}',
  },
];

// ── 24 Instrument Definitions ────────────────────────────────────────────────

export const INSTRUMENTS: readonly InstrumentDefinition[] = [
  // ─── CONVEYANCE ──────────────────────────────────────────────────────────

  {
    id: 'sale_deed',
    category: 'conveyance',
    label: 'Sale Deed',
    section: 'Art. 20',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: true,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Transfer of immovable property by sale',
  },
  {
    id: 'agreement_to_sell_with_possession',
    category: 'conveyance',
    label: 'Agreement to Sell (with possession)',
    section: 'Art. 5(c)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: true,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Agreement to sell with delivery of possession — same duty as sale deed',
  },
  {
    id: 'agreement_to_sell_without_possession',
    category: 'conveyance',
    label: 'Agreement to Sell (without possession)',
    section: 'Art. 5(e)',
    dutyMethod: 'flat_percentage',
    rate: 0.001,
    minimumDuty: 500,
    requiresValue: true,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Agreement to sell without possession — 0.1% of consideration',
  },
  {
    id: 'joint_development_agreement',
    category: 'conveyance',
    label: 'Joint Development Agreement (JDA)',
    section: 'Art. 5(d-a)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Joint development agreement — duty on owner share market value',
  },
  {
    id: 'exchange_deed',
    category: 'conveyance',
    label: 'Exchange Deed',
    section: 'Art. 31',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Exchange of properties — duty on higher-valued property',
  },

  // ─── GIFT / RELEASE ──────────────────────────────────────────────────────

  {
    id: 'gift_deed',
    category: 'gift_release',
    label: 'Gift Deed',
    section: 'Art. 33',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    hasFamilyDistinction: true,
    familyDutyOverride: {
      dutyMethod: 'fixed_location',
      locationFees: FAMILY_LOCATION_FEES,
    },
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Gift of immovable property — family members get reduced fixed duty',
  },
  {
    id: 'release_deed',
    category: 'gift_release',
    label: 'Release Deed',
    section: 'Art. 55',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    hasFamilyDistinction: true,
    familyDutyOverride: {
      dutyMethod: 'fixed_location',
      locationFees: FAMILY_LOCATION_FEES,
    },
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Release of right in immovable property — family members get reduced fixed duty',
  },
  {
    id: 'settlement_deed',
    category: 'gift_release',
    label: 'Settlement Deed',
    section: 'Art. 58',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    hasFamilyDistinction: true,
    familyDutyOverride: {
      dutyMethod: 'fixed_location',
      locationFees: FAMILY_LOCATION_FEES,
    },
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Settlement of property — family members get reduced fixed duty',
  },

  // ─── MORTGAGE ────────────────────────────────────────────────────────────

  {
    id: 'mortgage_with_possession',
    category: 'mortgage',
    label: 'Mortgage with Possession',
    section: 'Art. 40(a)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Usufructuary mortgage — same duty as conveyance',
  },
  {
    id: 'mortgage_without_possession',
    category: 'mortgage',
    label: 'Mortgage without Possession',
    section: 'Art. 40(b)',
    dutyMethod: 'flat_percentage',
    rate: 0.005,
    minimumDuty: 100,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Simple mortgage / mortgage by conditional sale — 0.5% of loan amount',
  },
  {
    id: 'deposit_title_deeds',
    category: 'mortgage',
    label: 'Deposit of Title Deeds',
    section: 'Art. 6',
    dutyMethod: 'flat_percentage',
    rate: 0.005,
    minimumDuty: 100,
    requiresValue: true,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Equitable mortgage by deposit of title deeds — 0.5% of loan amount',
  },

  // ─── LEASE ───────────────────────────────────────────────────────────────

  {
    id: 'lease_short_term',
    category: 'lease',
    label: 'Transfer of Lease (up to 30 years)',
    section: 'Art. 35(a)',
    dutyMethod: 'flat_percentage',
    rate: 0.02,
    requiresValue: true,
    requiresLocation: true,
    requiresLeaseTerms: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Lease for a term up to 30 years — 2% of total rent + premium',
  },
  {
    id: 'lease_long_term',
    category: 'lease',
    label: 'Transfer of Lease (above 30 years)',
    section: 'Art. 35(b)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    requiresLeaseTerms: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Lease for a term above 30 years — same as conveyance duty',
  },
  {
    id: 'surrender_of_lease',
    category: 'lease',
    label: 'Surrender of Lease',
    section: 'Art. 61',
    dutyMethod: 'flat_percentage',
    rate: 0.035,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Surrender of lease — 3.5% of value',
  },

  // ─── POWER OF ATTORNEY ───────────────────────────────────────────────────

  {
    id: 'poa_property_sale',
    category: 'power_of_attorney',
    label: 'POA for Property Sale',
    section: 'Art. 48(b)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Power of attorney to sell immovable property — same as conveyance duty',
  },
  {
    id: 'poa_standard',
    category: 'power_of_attorney',
    label: 'General Power of Attorney',
    section: 'Art. 48(a)',
    dutyMethod: 'fixed_amount',
    fixedDuty: 500,
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'General POA not involving sale of immovable property',
  },

  // ─── PARTITION ───────────────────────────────────────────────────────────

  {
    id: 'partition_non_agriculture',
    category: 'partition',
    label: 'Partition (Non-Agriculture)',
    section: 'Art. 43(b)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    requiresShareCount: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Partition of non-agriculture property — duty on separated share value',
  },
  {
    id: 'partition_agriculture',
    category: 'partition',
    label: 'Partition (Agriculture)',
    section: 'Art. 43(a)',
    dutyMethod: 'fixed_amount',
    fixedDuty: 1000,
    requiresValue: false,
    requiresLocation: false,
    requiresShareCount: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Partition of agriculture land — fixed duty of Rs 1,000 per share',
  },

  // ─── TRUST & WILL ───────────────────────────────────────────────────────

  {
    id: 'trust_with_property',
    category: 'trust_will',
    label: 'Trust Deed (with property)',
    section: 'Art. 64(a)',
    dutyMethod: 'tiered_ad_valorem',
    tieredSlabs: SALE_DEED_SLABS,
    requiresValue: true,
    requiresLocation: true,
    scstRebateEligible: false,
    registrationFeeMethod: 'percentage',
    registrationFeeRate: 0.02,
    description: 'Trust deed involving transfer of property — same as conveyance',
  },
  {
    id: 'trust_no_property',
    category: 'trust_will',
    label: 'Trust Deed (without property)',
    section: 'Art. 64(b)',
    dutyMethod: 'fixed_amount',
    fixedDuty: 500,
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Trust deed not involving property transfer',
  },
  {
    id: 'will_deed',
    category: 'trust_will',
    label: 'Will Deed',
    section: 'Art. 64-A',
    dutyMethod: 'nil',
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Will — no stamp duty; optional registration with fixed fee',
  },
  {
    id: 'cancellation_of_will',
    category: 'trust_will',
    label: 'Cancellation of Will',
    section: 'Art. 17',
    dutyMethod: 'fixed_amount',
    fixedDuty: 500,
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Cancellation or revocation of a will',
  },

  // ─── MISCELLANEOUS ───────────────────────────────────────────────────────

  {
    id: 'adoption_deed',
    category: 'miscellaneous',
    label: 'Adoption Deed',
    section: 'Art. 3',
    dutyMethod: 'fixed_amount',
    fixedDuty: 500,
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'fixed',
    registrationFeeFixed: 200,
    description: 'Deed of adoption',
  },
  {
    id: 'affidavit',
    category: 'miscellaneous',
    label: 'Affidavit',
    section: 'Art. 4',
    dutyMethod: 'fixed_amount',
    fixedDuty: 100,
    requiresValue: false,
    requiresLocation: false,
    scstRebateEligible: false,
    registrationFeeMethod: 'nil',
    description: 'Affidavit — fixed stamp duty, no registration',
  },
];

// ── Lookup Helpers ───────────────────────────────────────────────────────────

export function getInstrumentById(id: string): InstrumentDefinition | undefined {
  return INSTRUMENTS.find((inst) => inst.id === id);
}

export function getInstrumentsByCategory(category: StampCategory): readonly InstrumentDefinition[] {
  return INSTRUMENTS.filter((inst) => inst.category === category);
}

export function getCategoryById(id: StampCategory): StampCategoryInfo | undefined {
  return STAMP_CATEGORIES.find((cat) => cat.id === id);
}
